#include <stdio.h>
int main() {
	asm volatile(
		".section .data;"
		"format: .string \"%d\";"
		"x: .quad 0;"
		"_t0: .quad 0;"
		"_t1: .quad 0;"
		"y: .quad 0;"
		"_t2: .quad 0;"
		"z: .quad 0;"
		".section .text;"
		"BBlock0x107fc30:;"
		"movq $7, %r8;"
		"movq %r8, x;"
		"movq $10, %r8;"
		"movq x, %r9;"
		"addq %r9, %r8;"
		"movq %r8, _t0;"
		"movq _t0, %rax;"
		"movq $2, %rbx;"
		"mulq %rbx ;"
		"movq %rax, _t1;"
		"movq _t1, %r8;"
		"movq %r8, y;"
		"movq y, %r8;"
		"movq x, %r9;"
		"subq %r9, %r8;"
		"movq %r8, _t2;"
		"movq _t2, %r8;"
		"movq %r8, z;"
		"pushq %rbx;"
		"leaq  format(%rip), %rdi;"
		"mov z, %esi;"
		"xor   %eax, %eax;"
		"call  printf;"
		"popq  %rbx;"
	);
}